export const HISTORY_GENEALOGY_PLAYS = [
  { slug: "king-john", title: "King John" },
  { slug: "richard-ii", title: "Richard II" },
  { slug: "henry-iv-part-i", title: "Henry IV, Part 1" },
  { slug: "henry-iv-part-ii", title: "Henry IV, Part 2" },
  { slug: "henry-v", title: "Henry V" },
  { slug: "henry-vi-part-i", title: "Henry VI, Part 1" },
  { slug: "henry-vi-part-ii", title: "Henry VI, Part 2" },
  { slug: "henry-vi-part-iii", title: "Henry VI, Part 3" },
  { slug: "richard-iii", title: "Richard III" },
  { slug: "henry-viii", title: "Henry VIII" },
];

export const HISTORY_GENEALOGY_HOUSES = {
  angevin: { label: "Angevin / Early Plantagenet", shortLabel: "Angevin", fill: "#7a2e1e", stroke: "#5f2012", text: "#fff8f0" },
  plantagenet: { label: "Plantagenet", shortLabel: "Plantagenet", fill: "#8b3e2f", stroke: "#642619", text: "#fff8f0" },
  lancaster: { label: "Lancaster", shortLabel: "Lancaster", fill: "#b17f18", stroke: "#7d590f", text: "#fff8f0" },
  york: { label: "York", shortLabel: "York", fill: "#375d93", stroke: "#27436b", text: "#f7fbff" },
  tudor: { label: "Tudor", shortLabel: "Tudor", fill: "#376a43", stroke: "#23452b", text: "#f3fbf4" },
  foreign: { label: "Marriage / Foreign House", shortLabel: "Marriage", fill: "#79658f", stroke: "#5d4b70", text: "#f8f2ff" },
  context: { label: "Context Figure", shortLabel: "Context", fill: "#6c6257", stroke: "#4f473f", text: "#fffaf1" },
};

export const HISTORY_GENEALOGY_REGNAL_LINE = [
  "john",
  "henry-iii",
  "edward-i",
  "edward-ii",
  "edward-iii",
  "richard-ii",
  "henry-iv",
  "henry-v",
  "henry-vi",
  "edward-iv",
  "edward-v",
  "richard-iii",
  "henry-vii",
  "henry-viii",
];

export const HISTORY_GENEALOGY_NODES = [
  {
    id: "henry-ii",
    name: "Henry II",
    displayName: "Henry II",
    role: "King of England",
    house: "angevin",
    x: 120,
    y: 500,
    workSlugs: [],
    summary: "Context only. His sons John's and Geoffrey's lines matter for the crisis of King John.",
  },
  {
    id: "eleanor-aquitaine",
    name: "Eleanor of Aquitaine",
    displayName: "Eleanor of\nAquitaine",
    role: "Queen Mother",
    house: "foreign",
    x: 120,
    y: 620,
    workSlugs: ["king-john"],
    summary: "John's mother, and one of the most formidable elder stateswomen in the histories.",
  },
  {
    id: "geoffrey-brittany",
    name: "Geoffrey of Brittany",
    displayName: "Geoffrey of\nBrittany",
    role: "Context Prince",
    house: "angevin",
    x: 330,
    y: 340,
    workSlugs: [],
    summary: "John's elder brother and Arthur's father; his line creates the rival claim in King John.",
  },
  {
    id: "john",
    name: "John",
    displayName: "King John",
    role: "King of England",
    house: "angevin",
    x: 330,
    y: 620,
    workSlugs: ["king-john"],
    summary: "The embattled king whose disputed title and treatment of Arthur shadow the whole play.",
  },
  {
    id: "constance",
    name: "Constance",
    displayName: "Constance",
    role: "Duchess of Brittany",
    house: "foreign",
    x: 560,
    y: 220,
    workSlugs: ["king-john"],
    summary: "Arthur's mother, who insists on her son's hereditary claim against John.",
  },
  {
    id: "arthur",
    name: "Arthur",
    displayName: "Arthur",
    role: "Claimant to the Crown",
    house: "angevin",
    x: 770,
    y: 220,
    workSlugs: ["king-john"],
    summary: "Geoffrey's son and John's nephew, treated as the hereditary alternative to John.",
  },
  {
    id: "henry-iii",
    name: "Henry III",
    displayName: "Henry III",
    role: "King of England",
    house: "plantagenet",
    x: 560,
    y: 760,
    workSlugs: [],
    summary: "Context only. John's son, through whom the later Plantagenet line continues.",
  },
  {
    id: "edward-i",
    name: "Edward I",
    displayName: "Edward I",
    role: "King of England",
    house: "plantagenet",
    x: 770,
    y: 760,
    workSlugs: [],
    summary: "Context only. His descendants dominate the later history cycle.",
  },
  {
    id: "edward-ii",
    name: "Edward II",
    displayName: "Edward II",
    role: "King of England",
    house: "plantagenet",
    x: 980,
    y: 760,
    workSlugs: [],
    summary: "Context only. Father of Edward III.",
  },
  {
    id: "edward-iii",
    name: "Edward III",
    displayName: "Edward III",
    role: "King of England",
    house: "plantagenet",
    x: 1190,
    y: 760,
    workSlugs: [],
    summary: "The great dynastic pivot. Shakespeare's later kings descend from competing branches of his family.",
  },
  {
    id: "black-prince",
    name: "Edward, the Black Prince",
    displayName: "Edward,\nthe Black Prince",
    role: "Prince of Wales",
    house: "plantagenet",
    x: 1420,
    y: 520,
    workSlugs: [],
    summary: "Edward III's eldest son and Richard II's father.",
  },
  {
    id: "richard-ii",
    name: "Richard II",
    displayName: "Richard II",
    role: "King of England",
    house: "plantagenet",
    x: 1650,
    y: 520,
    workSlugs: ["richard-ii"],
    summary: "The childless king whose deposition opens the Lancastrian sequence.",
  },
  {
    id: "lionel-clarence",
    name: "Lionel of Antwerp",
    displayName: "Lionel of\nClarence",
    role: "Duke of Clarence",
    house: "plantagenet",
    x: 1420,
    y: 180,
    workSlugs: [],
    summary: "Edward III's second surviving son. His line grounds the Mortimer and Yorkist hereditary claims.",
  },
  {
    id: "philippa-clarence",
    name: "Philippa of Clarence",
    displayName: "Philippa of\nClarence",
    role: "Heiress of Lionel's Line",
    house: "plantagenet",
    x: 1650,
    y: 180,
    workSlugs: [],
    summary: "Lionel's daughter; through her the Mortimers and then the Yorkists inherit a superior hereditary claim.",
  },
  {
    id: "roger-mortimer",
    name: "Roger Mortimer",
    displayName: "Roger\nMortimer",
    role: "Earl of March",
    house: "plantagenet",
    x: 1880,
    y: 180,
    workSlugs: [],
    summary: "Grandson of Philippa. Father of Edmund Mortimer and Anne Mortimer.",
  },
  {
    id: "edmund-mortimer",
    name: "Edmund Mortimer",
    displayName: "Edmund\nMortimer",
    role: "Earl of March",
    house: "plantagenet",
    x: 2110,
    y: 100,
    workSlugs: ["henry-iv-part-i"],
    summary: "The heir presumptive by strict descent from Lionel of Clarence, though politically displaced by Bolingbroke.",
  },
  {
    id: "anne-mortimer",
    name: "Anne Mortimer",
    displayName: "Anne\nMortimer",
    role: "Mortimer Heiress",
    house: "plantagenet",
    x: 2110,
    y: 260,
    workSlugs: [],
    summary: "Sister of Edmund Mortimer; through her marriage, the Yorkist line inherits the Mortimer claim.",
  },
  {
    id: "john-gaunt",
    name: "John of Gaunt",
    displayName: "John of\nGaunt",
    role: "Duke of Lancaster",
    house: "lancaster",
    x: 1420,
    y: 760,
    workSlugs: ["richard-ii"],
    summary: "Edward III's son and founder of the Lancastrian royal line in Shakespeare's histories.",
  },
  {
    id: "henry-iv",
    name: "Henry IV",
    displayName: "Henry IV",
    role: "King of England",
    house: "lancaster",
    x: 1650,
    y: 760,
    workSlugs: ["richard-ii", "henry-iv-part-i", "henry-iv-part-ii"],
    summary: "Bolingbroke, son of John of Gaunt, who takes Richard II's crown and founds the Lancastrian kingship.",
  },
  {
    id: "henry-v",
    name: "Henry V",
    displayName: "Henry V",
    role: "King of England",
    house: "lancaster",
    x: 1880,
    y: 760,
    workSlugs: ["henry-iv-part-i", "henry-iv-part-ii", "henry-v"],
    summary: "Prince Hal become king: the great Lancastrian hero, father of Henry VI.",
  },
  {
    id: "catherine-valois",
    name: "Catherine of Valois",
    displayName: "Catherine of\nValois",
    role: "Queen of England",
    house: "foreign",
    x: 1880,
    y: 900,
    workSlugs: ["henry-v"],
    summary: "French princess who marries Henry V and becomes mother of Henry VI.",
  },
  {
    id: "henry-vi",
    name: "Henry VI",
    displayName: "Henry VI",
    role: "King of England",
    house: "lancaster",
    x: 2110,
    y: 760,
    workSlugs: ["henry-vi-part-i", "henry-vi-part-ii", "henry-vi-part-iii"],
    summary: "The pious but politically weak Lancastrian king whose reign collapses into civil war.",
  },
  {
    id: "margaret-anjou",
    name: "Margaret of Anjou",
    displayName: "Margaret of\nAnjou",
    role: "Queen of England",
    house: "foreign",
    x: 2110,
    y: 840,
    workSlugs: ["henry-vi-part-i", "henry-vi-part-ii", "henry-vi-part-iii", "richard-iii"],
    summary: "Henry VI's queen, fierce defender of the Lancastrian cause, and a haunting survivor in Richard III.",
  },
  {
    id: "edward-westminster",
    name: "Edward of Westminster",
    displayName: "Edward of\nWestminster",
    role: "Prince of Wales",
    house: "lancaster",
    x: 2340,
    y: 840,
    workSlugs: ["henry-vi-part-iii"],
    summary: "Only son of Henry VI and Margaret, and the Lancastrian heir cut down in the wars.",
  },
  {
    id: "edmund-langley",
    name: "Edmund of Langley",
    displayName: "Edmund of\nLangley",
    role: "Duke of York",
    house: "york",
    x: 1420,
    y: 1020,
    workSlugs: ["richard-ii", "henry-iv-part-i", "henry-iv-part-ii"],
    summary: "Edward III's son and the elder root of the Yorkist branch. Shakespeare's Duke of York in Richard II is this Edmund.",
  },
  {
    id: "richard-conisburgh",
    name: "Richard of Conisburgh",
    displayName: "Richard of\nConisburgh",
    role: "Earl of Cambridge",
    house: "york",
    x: 1650,
    y: 1020,
    workSlugs: ["henry-v"],
    summary: "Edmund of Langley's son, executed in Henry V for the Southampton Plot.",
  },
  {
    id: "richard-york",
    name: "Richard Plantagenet",
    displayName: "Richard,\nDuke of York",
    role: "Yorkist Claimant",
    house: "york",
    x: 1880,
    y: 1020,
    workSlugs: ["henry-vi-part-i", "henry-vi-part-ii", "henry-vi-part-iii"],
    summary: "Father of Edward IV, Clarence, and Richard III. His title claim combines York and Mortimer descent.",
  },
  {
    id: "cecily-neville",
    name: "Cecily Neville",
    displayName: "Cecily\nNeville",
    role: "Duchess of York",
    house: "foreign",
    x: 1880,
    y: 1160,
    workSlugs: ["richard-iii"],
    summary: "Mother of Edward IV, Clarence, and Richard III; a living witness to York's disastrous triumph.",
  },
  {
    id: "edward-iv",
    name: "Edward IV",
    displayName: "Edward IV",
    role: "King of England",
    house: "york",
    x: 2110,
    y: 940,
    workSlugs: ["henry-vi-part-iii", "richard-iii"],
    summary: "York's eldest son who seizes the crown and fathers the princes whose deaths stain Richard III.",
  },
  {
    id: "george-clarence",
    name: "George, Duke of Clarence",
    displayName: "George,\nClarence",
    role: "Brother of Edward IV",
    house: "york",
    x: 2110,
    y: 1040,
    workSlugs: ["henry-vi-part-iii", "richard-iii"],
    summary: "Edward IV's brother, repeatedly shifting allegiance before dying under his brother and Richard's shadow.",
  },
  {
    id: "richard-iii",
    name: "Richard III",
    displayName: "Richard III",
    role: "King of England",
    house: "york",
    x: 2110,
    y: 1140,
    workSlugs: ["henry-vi-part-iii", "richard-iii"],
    summary: "Young Gloucester in Henry VI becomes Shakespeare's dazzling and murderous usurper in Richard III.",
  },
  {
    id: "elizabeth-woodville",
    name: "Elizabeth Woodville",
    displayName: "Elizabeth\nWoodville",
    role: "Queen of England",
    house: "foreign",
    x: 2340,
    y: 940,
    workSlugs: ["richard-iii"],
    summary: "Edward IV's widow, mother of the princes and of Elizabeth of York.",
  },
  {
    id: "edward-v",
    name: "Edward V",
    displayName: "Edward V",
    role: "Prince in the Tower",
    house: "york",
    x: 2570,
    y: 860,
    workSlugs: ["richard-iii"],
    summary: "Edward IV's elder son, never crowned in Shakespeare's story before Richard removes him.",
  },
  {
    id: "richard-shrewsbury",
    name: "Richard of Shrewsbury",
    displayName: "Richard of\nShrewsbury",
    role: "Prince in the Tower",
    house: "york",
    x: 2570,
    y: 960,
    workSlugs: ["richard-iii"],
    summary: "The younger prince, paired with Edward V as one of the victims of Richard's accession.",
  },
  {
    id: "elizabeth-york",
    name: "Elizabeth of York",
    displayName: "Elizabeth of\nYork",
    role: "Yorkist Heiress",
    house: "york",
    x: 2570,
    y: 1060,
    workSlugs: ["richard-iii"],
    summary: "Edward IV's daughter, later wife of Henry VII and key to the Tudor settlement.",
  },
  {
    id: "anne-neville",
    name: "Anne Neville",
    displayName: "Anne\nNeville",
    role: "Queen of England",
    house: "foreign",
    x: 2340,
    y: 1140,
    workSlugs: ["richard-iii"],
    summary: "Widow of Prince Edward of Lancaster, then queen to Richard III.",
  },
  {
    id: "henry-vii",
    name: "Henry VII",
    displayName: "Henry VII",
    role: "King of England",
    house: "tudor",
    x: 2800,
    y: 1060,
    workSlugs: ["richard-iii", "henry-viii"],
    summary: "Richmond in Richard III. His marriage to Elizabeth of York symbolically closes the civil wars.",
  },
  {
    id: "henry-viii",
    name: "Henry VIII",
    displayName: "Henry VIII",
    role: "King of England",
    house: "tudor",
    x: 3030,
    y: 1060,
    workSlugs: ["henry-viii"],
    summary: "The Tudor king at the far end of the history cycle, shown amid divorce, remarriage, and succession anxieties.",
  },
  {
    id: "katherine-aragon",
    name: "Katherine of Aragon",
    displayName: "Katherine of\nAragon",
    role: "Queen of England",
    house: "foreign",
    x: 3030,
    y: 940,
    workSlugs: ["henry-viii"],
    summary: "Henry VIII's first queen, treated with deep pathos in the play.",
  },
  {
    id: "anne-boleyn",
    name: "Anne Boleyn",
    displayName: "Anne\nBoleyn",
    role: "Queen of England",
    house: "foreign",
    x: 3030,
    y: 1180,
    workSlugs: ["henry-viii"],
    summary: "Anne Bullen in the play, whose rise ushers in the birth of Elizabeth.",
  },
  {
    id: "elizabeth-i",
    name: "Elizabeth I",
    displayName: "Elizabeth I",
    role: "Princess Elizabeth",
    house: "tudor",
    x: 3260,
    y: 1180,
    workSlugs: ["henry-viii"],
    summary: "Shown as the infant Princess Elizabeth in Henry VIII, but understood as the Tudor future.",
  },
];

export const HISTORY_GENEALOGY_EDGES = [
  { id: "e1", source: "henry-ii", target: "eleanor-aquitaine", type: "spouse" },
  { id: "e2", source: "henry-ii", target: "john", type: "parent" },
  { id: "e3", source: "eleanor-aquitaine", target: "john", type: "parent" },
  { id: "e4", source: "henry-ii", target: "geoffrey-brittany", type: "parent" },
  { id: "e5", source: "eleanor-aquitaine", target: "geoffrey-brittany", type: "parent" },
  { id: "e6", source: "geoffrey-brittany", target: "constance", type: "spouse" },
  { id: "e7", source: "geoffrey-brittany", target: "arthur", type: "parent" },
  { id: "e8", source: "constance", target: "arthur", type: "parent" },
  { id: "e9", source: "john", target: "henry-iii", type: "parent" },
  { id: "e10", source: "henry-iii", target: "edward-i", type: "parent" },
  { id: "e11", source: "edward-i", target: "edward-ii", type: "parent" },
  { id: "e12", source: "edward-ii", target: "edward-iii", type: "parent" },
  { id: "e13", source: "edward-iii", target: "black-prince", type: "parent" },
  { id: "e14", source: "black-prince", target: "richard-ii", type: "parent" },
  { id: "e15", source: "edward-iii", target: "lionel-clarence", type: "parent" },
  { id: "e16", source: "lionel-clarence", target: "philippa-clarence", type: "parent" },
  { id: "e17", source: "philippa-clarence", target: "roger-mortimer", type: "parent" },
  { id: "e18", source: "roger-mortimer", target: "edmund-mortimer", type: "parent" },
  { id: "e19", source: "roger-mortimer", target: "anne-mortimer", type: "parent" },
  { id: "e20", source: "edward-iii", target: "john-gaunt", type: "parent" },
  { id: "e21", source: "john-gaunt", target: "henry-iv", type: "parent" },
  { id: "e22", source: "henry-iv", target: "henry-v", type: "parent" },
  { id: "e23", source: "henry-v", target: "catherine-valois", type: "spouse" },
  { id: "e24", source: "henry-v", target: "henry-vi", type: "parent" },
  { id: "e25", source: "catherine-valois", target: "henry-vi", type: "parent" },
  { id: "e26", source: "henry-vi", target: "margaret-anjou", type: "spouse" },
  { id: "e27", source: "henry-vi", target: "edward-westminster", type: "parent" },
  { id: "e28", source: "margaret-anjou", target: "edward-westminster", type: "parent" },
  { id: "e29", source: "edward-iii", target: "edmund-langley", type: "parent" },
  { id: "e30", source: "edmund-langley", target: "richard-conisburgh", type: "parent" },
  { id: "e31", source: "richard-conisburgh", target: "anne-mortimer", type: "spouse" },
  { id: "e32", source: "richard-conisburgh", target: "richard-york", type: "parent" },
  { id: "e33", source: "anne-mortimer", target: "richard-york", type: "parent" },
  { id: "e34", source: "richard-york", target: "cecily-neville", type: "spouse" },
  { id: "e35", source: "richard-york", target: "edward-iv", type: "parent" },
  { id: "e36", source: "cecily-neville", target: "edward-iv", type: "parent" },
  { id: "e37", source: "richard-york", target: "george-clarence", type: "parent" },
  { id: "e38", source: "cecily-neville", target: "george-clarence", type: "parent" },
  { id: "e39", source: "richard-york", target: "richard-iii", type: "parent" },
  { id: "e40", source: "cecily-neville", target: "richard-iii", type: "parent" },
  { id: "e41", source: "edward-iv", target: "elizabeth-woodville", type: "spouse" },
  { id: "e42", source: "edward-iv", target: "edward-v", type: "parent" },
  { id: "e43", source: "elizabeth-woodville", target: "edward-v", type: "parent" },
  { id: "e44", source: "edward-iv", target: "richard-shrewsbury", type: "parent" },
  { id: "e45", source: "elizabeth-woodville", target: "richard-shrewsbury", type: "parent" },
  { id: "e46", source: "edward-iv", target: "elizabeth-york", type: "parent" },
  { id: "e47", source: "elizabeth-woodville", target: "elizabeth-york", type: "parent" },
  { id: "e48", source: "richard-iii", target: "anne-neville", type: "spouse" },
  { id: "e49", source: "henry-vii", target: "elizabeth-york", type: "spouse" },
  { id: "e50", source: "henry-vii", target: "henry-viii", type: "parent" },
  { id: "e51", source: "elizabeth-york", target: "henry-viii", type: "parent" },
  { id: "e52", source: "henry-viii", target: "katherine-aragon", type: "spouse" },
  { id: "e53", source: "henry-viii", target: "anne-boleyn", type: "spouse" },
  { id: "e54", source: "henry-viii", target: "elizabeth-i", type: "parent" },
  { id: "e55", source: "anne-boleyn", target: "elizabeth-i", type: "parent" },
];

export function getHistoryPlayTitle(slug) {
  return HISTORY_GENEALOGY_PLAYS.find((play) => play.slug === slug)?.title || slug;
}
