const GLOSSARY = {
  "thee":"You (singular, objective case — used for familiarity or to address inferiors).",
  "thou":"You (singular, subjective case — intimate or informal).",
  "thy":"Your (singular possessive).",
  "thine":"Yours, or your (before a vowel sound).",
  "hath":"Has.",
  "doth":"Does.",
  "art":"Are (second person singular: 'thou art').",
  "ere":"Before.",
  "hither":"To this place; here.",
  "thither":"To that place; there.",
  "whither":"To where; to what place.",
  "hence":"From this place; away.",
  "thence":"From that place.",
  "wherefore":"Why; for what reason. (Not 'where'.)",
  "prithee":"I pray thee; please.",
  "forsooth":"In truth; indeed.",
  "anon":"Soon; shortly.",
  "betwixt":"Between.",
  "methinks":"It seems to me.",
  "perchance":"Perhaps.",
  "marry":"Indeed! (mild oath, from the Virgin Mary).",
  "sirrah":"Form of address to an inferior.",
  "withal":"With; in addition; moreover.",
  "aught":"Anything.",
  "naught":"Nothing.",
  "nay":"No.",
  "ay":"Yes.",
  "aye":"Yes; ever.",
  "fie":"Exclamation of disgust or disapproval.",
  "wilt":"Will (second person: 'thou wilt').",
  "shalt":"Shall (second person: 'thou shalt').",
  "dost":"Do (second person: 'thou dost').",
  "hast":"Have (second person: 'thou hast').",
  "wert":"Were (second person: 'thou wert').",
  "wouldst":"Would (second person: 'thou wouldst').",
  "shouldst":"Should (second person).",
  "mayhap":"Perhaps.",
  "'twas":"It was.",
  "'tis":"It is.",
  "o'er":"Over.",
  "ne'er":"Never.",
  "e'er":"Ever.",
  "oft":"Often.",
  "fain":"Gladly; willing.",
  "knave":"A dishonest or unscrupulous man; a male servant.",
  "varlet":"A rascal; an attendant.",
  "wench":"A girl or young woman.",
  "coz":"Cousin (term of familiar address).",
  "troth":"Truth, faith (as in 'by my troth').",
  "alack":"Alas; an exclamation of regret.",
  "lass":"A girl or young woman.",
  "lief":"Gladly; willingly ('I had as lief').",
  "mark":"Listen; pay attention to.",
  "morrow":"Morning ('good morrow').",
  "pox":"A curse (as in 'a pox upon it').",
  "rogue":"A dishonest or playfully mischievous person.",
  "sooth":"Truth.",
  "swain":"A young lover or suitor; a country youth.",
  "trow":"Believe; trust.",
  "verily":"Truly; certainly.",
  "villain":"Originally: a peasant; later: a scoundrel.",
  "visage":"Face; appearance.",
  "woe":"Grief; sorrow.",
  "yonder":"Over there; at a distance.",
  "zounds":"God's wounds (an oath).",
  "whence":"From where.",
  "abide":"To stay; to endure; to wait for.",
  "accost":"To approach and address.",
  "beseech":"To beg; to implore.",
  "beshrew":"A mild curse ('beshrew me').",
  "bestow":"To give; to place.",
  "entreat":"To ask earnestly; to plead.",
  "tarry":"To wait; to delay.",
};

function getGlossEntry(word) {
  return GLOSSARY[String(word || "").toLowerCase()] || null;
}

module.exports = {
  GLOSSARY,
  getGlossEntry,
};
